In [12]:

import pandas as pd
import numpy as np

print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

In [13]:

# Carregar os dados dos sensores industriais
df = pd.read_csv("dados_sensores_metaltech.csv")

print("Arquivo carregado com sucesso!")
print(f"Quantidade de linhas: {df.shape[0]}")
print(f"Quantidade de colunas: {df.shape[1]}")

Arquivo carregado com sucesso!
Quantidade de linhas: 10000
Quantidade de colunas: 6

In [14]:

df.head()

,timestamp,id_maquina,temperatura_c,vibracao_mm_s,pressao_bar,falha_motor
0,2026-01-01 00:00:00,M03,67.015129,1.523088,40.672538,0
1,2026-01-01 00:01:00,M04,58.048478,2.738448,38.644490,0
2,2026-01-01 00:02:00,M01,67.938896,2.566715,46.814723,0
3,2026-01-01 00:03:00,M03,74.567369,3.174506,35.055251,0
4,2026-01-01 00:04:00,M03,72.688150,4.642862,42.926834,0

In [15]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      10000 non-null  object
 1   id_maquina     10000 non-null  object
 2   temperatura_c  9704 non-null   float64
 3   vibracao_mm_s  9701 non-null   float64
 4   pressao_bar    9700 non-null   float64
 5   falha_motor    10000 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 468.9+ KB

In [16]:

print("Valores ausentes por coluna:")
print(df.isnull().sum())

Valores ausentes por coluna:
timestamp          0
id_maquina         0
temperatura_c    296
vibracao_mm_s    299
pressao_bar      300
falha_motor        0
dtype: int64

In [17]:

print("Colunas disponíveis:")
print(df.columns.tolist())

print("\nPrimeiras linhas:")
display(df.head())

print("\nTipos de dados:")
print(df.dtypes)

Colunas disponíveis:
['timestamp', 'id_maquina', 'temperatura_c', 'vibracao_mm_s', 'pressao_bar', 'falha_motor']

Primeiras linhas:

,timestamp,id_maquina,temperatura_c,vibracao_mm_s,pressao_bar,falha_motor
0,2026-01-01 00:00:00,M03,67.015129,1.523088,40.672538,0
1,2026-01-01 00:01:00,M04,58.048478,2.738448,38.644490,0
2,2026-01-01 00:02:00,M01,67.938896,2.566715,46.814723,0
3,2026-01-01 00:03:00,M03,74.567369,3.174506,35.055251,0
4,2026-01-01 00:04:00,M03,72.688150,4.642862,42.926834,0

Tipos de dados:
timestamp         object
id_maquina        object
temperatura_c    float64
vibracao_mm_s    float64
pressao_bar      float64
falha_motor        int64
dtype: object

In [18]:

# Converte a coluna de tempo para o formato datetime
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Ordenar os registros por máquina e tempo
df = df.sort_values(["id_maquina", "timestamp"]).reset_index(drop=True)

print("Dados ordenados por máquina e tempo.")
display(df.head())

Dados ordenados por máquina e tempo.

,timestamp,id_maquina,temperatura_c,vibracao_mm_s,pressao_bar,falha_motor
0,2026-01-01 00:02:00,M01,67.938896,2.566715,46.814723,0
1,2026-01-01 00:06:00,M01,68.600033,4.367980,42.355141,0
2,2026-01-01 00:07:00,M01,63.604846,3.284385,40.326861,0
3,2026-01-01 00:15:00,M01,NaN,3.412334,36.503412,0
4,2026-01-01 00:21:00,M01,73.844198,3.040572,NaN,0

In [19]:

# Colunas numéricas dos sensores
sensores = [
    "temperatura_c",
    "vibracao_mm_s",
    "pressao_bar"
]

# Interpolar os valores ausentes separadamente por máquina
for coluna in sensores:
    df[coluna] = df.groupby("id_maquina")[coluna].transform(
        lambda serie: serie.interpolate(limit_direction="both")
    )

print("Valores ausentes após a interpolação:")
print(df[sensores].isnull().sum())

Valores ausentes após a interpolação:
temperatura_c    0
vibracao_mm_s    0
pressao_bar      0
dtype: int64

In [20]:

print("Total de valores ausentes no dataset:")
print(df.isnull().sum())

print("\nTotal de valores ausentes:")
print(df.isnull().sum().sum())

Total de valores ausentes no dataset:
timestamp        0
id_maquina       0
temperatura_c    0
vibracao_mm_s    0
pressao_bar      0
falha_motor      0
dtype: int64

Total de valores ausentes:
0

In [21]:

# Verificar estatísticas das variáveis dos sensores
display(df[sensores].describe())

# Contar temperaturas suspeitas
print("Temperaturas iguais a 999.9:")
print((df["temperatura_c"] == 999.9).sum())

# Contar vibrações negativas
print("\nVibrações negativas:")
print((df["vibracao_mm_s"] < 0).sum())

# Contar pressões negativas
print("\nPressões negativas:")
print((df["pressao_bar"] < 0).sum())

       temperatura_c  vibracao_mm_s   pressao_bar
count   10000.000000   10000.000000  10000.000000
mean       81.032217       2.920697     41.677647
std        93.034542       5.767929      8.160043
min        50.387999     -50.000000     26.603188
25%        66.859274       2.670221     38.056100
50%        70.345222       3.025688     40.210445
75%        74.088231       3.401842     42.364904
max       999.900000      21.386227    102.177445

Temperaturas iguais a 999.9:
100

Vibrações negativas:
104

Pressões negativas:
0

In [ ]:

# Recarregar os dados originais para refazer o tratamento corretamente
df = pd.read_csv("dados_sensores_metaltech.csv")

# Converter a coluna de tempo
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Ordenar por máquina e tempo
df = df.sort_values(
    ["id_maquina", "timestamp"]
).reset_index(drop=True)

# Definir as colunas dos sensores
sensores = [
    "temperatura_c",
    "vibracao_mm_s",
    "pressao_bar"
]

# Transformar medições inválidas em valores ausentes
df.loc[df["temperatura_c"] == 999.9, "temperatura_c"] = np.nan
df.loc[df["vibracao_mm_s"] < 0, "vibracao_mm_s"] = np.nan

# Interpolar os valores ausentes por máquina
for coluna in sensores:
    df[coluna] = df.groupby("id_maquina")[coluna].transform(
        lambda serie: serie.interpolate(limit_direction="both")
    )

# Conferir os resultados
print("Valores ausentes após o tratamento:")
print(df.isnull().sum())

print("\nTemperaturas iguais a 999.9:",
      (df["temperatura_c"] == 999.9).sum())

print("Vibrações negativas:",
      (df["vibracao_mm_s"] < 0).sum())

print("\nDimensões finais:", df.shape)